apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-run-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-dev
    profiles: [dev]
    strategy:
      standard:
        verify: true
        postdeploy:
          actions: ["postdeploy-make-cloud-run-services-public"]
  - targetId: run-prod-multi
    profiles: [prod]
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [10, 50]
          verify: false
          postdeploy:
            actions: ["postdeploy-make-cloud-run-services-public"]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-dev
description: Cloud Run development service
run:
  location: projects/PROJECT_ID/locations/asia-northeast1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: run-prod-multi
description: Cloud Run production service in Tokyo and Osaka
requireApproval: true
multiTarget:
 targetIds: [ run-prod-tok, run-prod-osa ]

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-prod-tok
description: Cloud Run production service in Tokyo
run:
  location: projects/PROJECT_ID/locations/asia-northeast1

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-prod-osa
description: Cloud Run production service in Osaka
run:
  location: projects/PROJECT_ID/locations/asia-northeast2

---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: my-run-demo-app-1/promote
description: Promotes a release to the next target
suspended: false
serviceAccount: PROJECT_NUMBER-compute@developer.gserviceaccount.com
selector:
- target:
    id: run-dev
rules:
- promoteRelease:
    name: "promote-release"
    # wait: 1m
    toTargetId: "@next"
---

apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: my-run-demo-app-1/advance
description: advances a rollout
suspended: false
serviceAccount: PROJECT_NUMBER-compute@developer.gserviceaccount.com
selector:
- target:
    id: run-prod-multi
rules:
- advanceRollout:
    name: "advance-rollout"
    sourcePhases: ["canary-10", "canary-50"]
    wait: 1m